# Generated by Django 3.0.3 on 2020-02-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=30, unique=True)),
                ('teacher_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
