# Generated by Django 3.0.3 on 2020-02-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher'),
        ('attendance', '0002_auto_20200229_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher'),
        ),
    ]
