# Generated by Django 3.0.3 on 2020-02-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher'),
        ('attendance', '0004_auto_20200229_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
